project:
  type: website

website: 
  page-navigation: true
  search: TRUE
  google-analytics: "G-8L8YC0LJJY"
  title: "Gustavo Frosi"
  navbar:
    logo: "ima/FS.png"
    left:
      - href: index.qmd
        text: Home
      - text: "CV"
        href: CV/index.qmd
      - sidebar:Projetos

  sidebar:
    - id: Projetos
      title: "Projetos"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - Projetos/um.qmd
        - Projetos/dois.qmd
        # navigation items

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



