project:
  type: website
  preview:
      port: 4444

lang: pt

website: 
  site-url: ""
  open-graph: true
  page-navigation: true
  search: TRUE
  google-analytics: "G-8L8YC0LJJY"
  page-footer: 
    left: "Website construído em [Quarto](https://quarto.org/), por Gustavo Frosi. Licença: [xxxx](https://creativecommons)."
    right: 
      - icon: github
        href: https://github.com/FGu5tav0
      - icon: envelope
        href: "mailto:gustavofrosi@hotmail.com"
    center: <img src="ima/FS.png" width="25" height="25" >
    
    
    
  title: "Gustavo Frosi"
  navbar:
    logo: "ima/FS2.png"
    left: 
      - text: "CV"
        href: CV/index.qmd
      - sidebar:Projetos
      - text: "Posts"
        href: recap.qmd

  sidebar:
    - id: Projetos
      title: "Projetos"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - Projetos/um.qmd
        - Projetos/dois.qmd
        # navigation items

format:
  html:
    theme:
      light: [lux, tema.scss]
      # dark: [lux, tema_dark.scss]
    # css: styles.css
    toc: true

# comments:
#   giscus:
#     repo: FGu5tav0

